"**":
  push:
    - name: maven-test
      runner:
        cpus: 4
      docker:
        image: maven:3.9-eclipse-temurin-17
        volumes:
          - .m2:/root/.m2:rw
      stages:
        - name: mvn-test
          script: mvn test -B

  pull_request:
    - name: maven-test
      runner:
        cpus: 4
      docker:
        image: maven:3.9-eclipse-temurin-17
        volumes:
          - .m2:/root/.m2:rw
      stages:
        - name: mvn-test
          script: mvn test -B
