global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: shiqian-gateway
    metrics_path: /actuator/prometheus
    static_configs:
      - targets:
          - host.docker.internal:8080
        labels:
          application: shiqian-gateway

  - job_name: shiqian-user
    metrics_path: /actuator/prometheus
    static_configs:
      - targets:
          - host.docker.internal:8081
        labels:
          application: shiqian-user

  - job_name: shiqian-resource
    metrics_path: /actuator/prometheus
    static_configs:
      - targets:
          - host.docker.internal:8082
        labels:
          application: shiqian-resource
