CREATE TABLE IF NOT EXISTS t_resource (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    title VARCHAR(200) NOT NULL,
    description VARCHAR(1000) DEFAULT NULL,
    summary VARCHAR(500) DEFAULT NULL,
    content_markdown LONGTEXT DEFAULT NULL,
    content_type VARCHAR(30) DEFAULT 'ARTICLE',
    content_scene VARCHAR(30) NOT NULL DEFAULT 'SHARE',
    tags VARCHAR(500) DEFAULT NULL,
    external_source VARCHAR(50) DEFAULT NULL,
    external_id VARCHAR(128) DEFAULT NULL,
    category_id BIGINT DEFAULT NULL,
    file_url VARCHAR(500) DEFAULT NULL,
    file_size BIGINT NOT NULL DEFAULT 0,
    file_type VARCHAR(100) DEFAULT NULL,
    download_count INT NOT NULL DEFAULT 0,
    view_count INT NOT NULL DEFAULT 0,
    version INT NOT NULL DEFAULT 1,
    status TINYINT NOT NULL DEFAULT 0,
    review_reason VARCHAR(500) DEFAULT NULL,
    reviewer_id BIGINT DEFAULT NULL,
    review_time DATETIME DEFAULT NULL,
    offline_reason VARCHAR(500) DEFAULT NULL,
    published_time DATETIME DEFAULT NULL,
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted TINYINT NOT NULL DEFAULT 0
);

CREATE INDEX IF NOT EXISTS idx_user_id ON t_resource(user_id);
CREATE UNIQUE INDEX IF NOT EXISTS uk_external_content ON t_resource(external_source, external_id);
CREATE INDEX IF NOT EXISTS idx_content_scene ON t_resource(content_scene);
CREATE INDEX IF NOT EXISTS idx_category_id ON t_resource(category_id);

-- 资源附件表（测试用）
CREATE TABLE IF NOT EXISTS t_resource_attachment (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    resource_id BIGINT NOT NULL,
    file_name VARCHAR(255) NOT NULL,
    file_url VARCHAR(500) NOT NULL,
    file_size BIGINT DEFAULT 0,
    file_type VARCHAR(100),
    mime_type VARCHAR(100),
    asset_kind VARCHAR(30) DEFAULT 'FILE',
    usage_type VARCHAR(30) DEFAULT 'ATTACHMENT',
    sort_order INT DEFAULT 0,
    create_time DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_resource_id ON t_resource_attachment(resource_id);

CREATE TABLE IF NOT EXISTS t_stored_object (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id CHAR(36) NOT NULL,
    owner_id BIGINT NOT NULL,
    resource_id BIGINT DEFAULT NULL,
    object_key VARCHAR(500) NOT NULL,
    original_name VARCHAR(255) NOT NULL,
    storage_provider VARCHAR(30) NOT NULL,
    bucket_name VARCHAR(100),
    file_size BIGINT NOT NULL,
    extension VARCHAR(20) NOT NULL,
    mime_type VARCHAR(100) NOT NULL,
    asset_kind VARCHAR(30) NOT NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'TEMPORARY',
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE UNIQUE INDEX IF NOT EXISTS uk_stored_object_public_id ON t_stored_object(public_id);
CREATE UNIQUE INDEX IF NOT EXISTS uk_stored_object_key ON t_stored_object(object_key);
CREATE INDEX IF NOT EXISTS idx_stored_object_owner_status ON t_stored_object(owner_id, status);
CREATE INDEX IF NOT EXISTS idx_stored_object_resource ON t_stored_object(resource_id, status);
CREATE INDEX IF NOT EXISTS idx_stored_object_cleanup ON t_stored_object(status, create_time);

CREATE TABLE IF NOT EXISTS t_user_storage_quota (
    owner_id BIGINT PRIMARY KEY,
    used_bytes BIGINT NOT NULL DEFAULT 0,
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS t_sensitive_word (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    word VARCHAR(100) NOT NULL,
    level TINYINT NOT NULL DEFAULT 2,
    status TINYINT NOT NULL DEFAULT 1,
    created_by BIGINT,
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted TINYINT NOT NULL DEFAULT 0
);
CREATE UNIQUE INDEX IF NOT EXISTS uk_sensitive_word ON t_sensitive_word(word);
CREATE INDEX IF NOT EXISTS idx_sensitive_word_status ON t_sensitive_word(status, deleted);

CREATE TABLE IF NOT EXISTS t_content_review_record (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    resource_id BIGINT,
    submitter_id BIGINT,
    reviewer_id BIGINT,
    review_type VARCHAR(20) NOT NULL,
    decision VARCHAR(30) NOT NULL,
    matched_words VARCHAR(1000),
    reason VARCHAR(500),
    content_title VARCHAR(200),
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_review_resource ON t_content_review_record(resource_id, create_time);
CREATE INDEX IF NOT EXISTS idx_review_type_decision ON t_content_review_record(review_type, decision, create_time);

CREATE TABLE IF NOT EXISTS t_category (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    parent_id BIGINT NOT NULL DEFAULT 0,
    name VARCHAR(100) NOT NULL,
    sort_order INT NOT NULL DEFAULT 0,
    icon VARCHAR(255) DEFAULT NULL,
    status TINYINT NOT NULL DEFAULT 1,
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted TINYINT NOT NULL DEFAULT 0
);

CREATE INDEX IF NOT EXISTS idx_parent_id ON t_category(parent_id);

CREATE TABLE IF NOT EXISTS t_tag (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    status TINYINT NOT NULL DEFAULT 1,
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted TINYINT NOT NULL DEFAULT 0
);
CREATE UNIQUE INDEX IF NOT EXISTS uk_tag_name ON t_tag(name);
CREATE INDEX IF NOT EXISTS idx_tag_status ON t_tag(status, deleted);

CREATE TABLE IF NOT EXISTS t_resource_category (
    resource_id BIGINT NOT NULL,
    category_id BIGINT NOT NULL,
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (resource_id, category_id)
);
CREATE INDEX IF NOT EXISTS idx_resource_category_category
    ON t_resource_category(category_id, resource_id);

CREATE TABLE IF NOT EXISTS t_resource_tag (
    resource_id BIGINT NOT NULL,
    tag_id BIGINT NOT NULL,
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (resource_id, tag_id)
);
CREATE INDEX IF NOT EXISTS idx_resource_tag_tag ON t_resource_tag(tag_id, resource_id);

CREATE TABLE IF NOT EXISTS t_resource_version (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    resource_id BIGINT NOT NULL,
    version_number INT NOT NULL,
    title VARCHAR(200) NOT NULL,
    summary VARCHAR(500),
    description VARCHAR(1000),
    markdown_content CLOB,
    category_id BIGINT,
    tags VARCHAR(500),
    content_scene VARCHAR(30) NOT NULL,
    resource_type VARCHAR(30) NOT NULL,
    file_url VARCHAR(500),
    file_size BIGINT NOT NULL DEFAULT 0,
    file_type VARCHAR(100),
    category_ids_json CLOB NOT NULL,
    tag_names_json CLOB NOT NULL,
    attachments_json CLOB NOT NULL,
    change_description VARCHAR(500),
    created_by BIGINT NOT NULL,
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE UNIQUE INDEX IF NOT EXISTS uk_resource_version
    ON t_resource_version(resource_id, version_number);
CREATE INDEX IF NOT EXISTS idx_resource_version_time
    ON t_resource_version(resource_id, create_time);

CREATE TABLE IF NOT EXISTS t_favorite (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    resource_id BIGINT NOT NULL,
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE UNIQUE INDEX IF NOT EXISTS uk_user_resource ON t_favorite(user_id, resource_id);
CREATE INDEX IF NOT EXISTS idx_resource_id ON t_favorite(resource_id);

CREATE TABLE IF NOT EXISTS t_admin_operation_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    operator_id BIGINT NOT NULL DEFAULT 0,
    operator_name VARCHAR(100) NOT NULL DEFAULT '系统',
    operation_type VARCHAR(100) NOT NULL,
    target_type VARCHAR(50),
    target_id BIGINT,
    detail VARCHAR(1000),
    request_method VARCHAR(10),
    request_uri VARCHAR(500),
    request_ip VARCHAR(64),
    request_params CLOB,
    result VARCHAR(30),
    error_message VARCHAR(1000),
    duration_ms BIGINT,
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_admin_log_operator ON t_admin_operation_log(operator_id);
CREATE INDEX IF NOT EXISTS idx_admin_log_type ON t_admin_operation_log(operation_type);
CREATE INDEX IF NOT EXISTS idx_admin_log_time ON t_admin_operation_log(create_time);

CREATE TABLE IF NOT EXISTS t_outbox_event (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    message_id VARCHAR(64) NOT NULL,
    event_type VARCHAR(64) NOT NULL,
    aggregate_type VARCHAR(32) NOT NULL DEFAULT 'RESOURCE',
    aggregate_id BIGINT NOT NULL,
    payload CLOB NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    retry_count INT NOT NULL DEFAULT 0,
    next_retry_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_error VARCHAR(1000),
    published_time DATETIME,
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE UNIQUE INDEX IF NOT EXISTS uk_outbox_message_id ON t_outbox_event(message_id);
CREATE INDEX IF NOT EXISTS idx_outbox_ready ON t_outbox_event(status, next_retry_time, id);

CREATE TABLE IF NOT EXISTS t_mq_consumed_message (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    message_id VARCHAR(64) NOT NULL,
    consumer_name VARCHAR(100) NOT NULL,
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE UNIQUE INDEX IF NOT EXISTS uk_consumed_message
    ON t_mq_consumed_message(message_id, consumer_name);

CREATE TABLE IF NOT EXISTS t_user_notification (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    message_id VARCHAR(64) NOT NULL,
    user_id BIGINT NOT NULL,
    notification_type VARCHAR(50) NOT NULL,
    title VARCHAR(200) NOT NULL,
    content VARCHAR(1000) NOT NULL,
    related_id BIGINT,
    read_flag TINYINT NOT NULL DEFAULT 0,
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE UNIQUE INDEX IF NOT EXISTS uk_notification_message
    ON t_user_notification(message_id);
CREATE INDEX IF NOT EXISTS idx_notification_user
    ON t_user_notification(user_id, read_flag, create_time);
