CREATE TABLE IF NOT EXISTS t_resource (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    title VARCHAR(200) NOT NULL,
    description VARCHAR(1000) DEFAULT NULL,
    summary VARCHAR(500) DEFAULT NULL,
    content_markdown LONGTEXT DEFAULT NULL,
    content_type VARCHAR(30) DEFAULT 'ARTICLE',
    content_scene VARCHAR(30) NOT NULL DEFAULT 'SHARE',
    tags VARCHAR(500) DEFAULT NULL,
    external_source VARCHAR(50) DEFAULT NULL,
    external_id VARCHAR(128) DEFAULT NULL,
    category_id BIGINT DEFAULT NULL,
    file_url VARCHAR(500) DEFAULT NULL,
    file_size BIGINT NOT NULL DEFAULT 0,
    file_type VARCHAR(100) DEFAULT NULL,
    download_count INT NOT NULL DEFAULT 0,
    view_count INT NOT NULL DEFAULT 0,
    version INT NOT NULL DEFAULT 1,
    status TINYINT NOT NULL DEFAULT 0,
    review_reason VARCHAR(500) DEFAULT NULL,
    reviewer_id BIGINT DEFAULT NULL,
    review_time DATETIME DEFAULT NULL,
    offline_reason VARCHAR(500) DEFAULT NULL,
    published_time DATETIME DEFAULT NULL,
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted TINYINT NOT NULL DEFAULT 0
);

CREATE INDEX IF NOT EXISTS idx_user_id ON t_resource(user_id);
CREATE UNIQUE INDEX IF NOT EXISTS uk_external_content ON t_resource(external_source, external_id);
CREATE INDEX IF NOT EXISTS idx_content_scene ON t_resource(content_scene);
CREATE INDEX IF NOT EXISTS idx_category_id ON t_resource(category_id);

-- 资源附件表（测试用）
CREATE TABLE IF NOT EXISTS t_resource_attachment (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    resource_id BIGINT NOT NULL,
    file_name VARCHAR(255) NOT NULL,
    file_url VARCHAR(500) NOT NULL,
    file_size BIGINT DEFAULT 0,
    file_type VARCHAR(100),
    mime_type VARCHAR(100),
    asset_kind VARCHAR(30) DEFAULT 'FILE',
    usage_type VARCHAR(30) DEFAULT 'ATTACHMENT',
    sort_order INT DEFAULT 0,
    create_time DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_resource_id ON t_resource_attachment(resource_id);

CREATE TABLE IF NOT EXISTS t_category (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    parent_id BIGINT NOT NULL DEFAULT 0,
    name VARCHAR(100) NOT NULL,
    sort_order INT NOT NULL DEFAULT 0,
    icon VARCHAR(255) DEFAULT NULL,
    status TINYINT NOT NULL DEFAULT 1,
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted TINYINT NOT NULL DEFAULT 0
);

CREATE INDEX IF NOT EXISTS idx_parent_id ON t_category(parent_id);

CREATE TABLE IF NOT EXISTS t_favorite (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    resource_id BIGINT NOT NULL,
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE UNIQUE INDEX IF NOT EXISTS uk_user_resource ON t_favorite(user_id, resource_id);
CREATE INDEX IF NOT EXISTS idx_resource_id ON t_favorite(resource_id);
